name: ecocycle_1
description: EcoCycle â€“ Smart waste & cloth recycling (Supabase + OSM)
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.5
  supabase_flutter: ^2.6.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geolocator: ^10.1.0
  flutter_animate: ^4.5.0
  intl: ^0.20.2
  image_picker: ^1.2.0
  url_launcher: ^6.1.10

  path: any
dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/images/ecocycle.png
